defaultTenant: biblus
dfdefaultTenant: biblus

tenants:
  datasources:
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
      
      
dftenants:
  datasources:
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_docflow_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike