defaultTenant: biblus

tenants:
  datasources:
    ess:
      url: jdbc:postgresql://188.169.57.232:5432/administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    biblus:
      url: jdbc:postgresql://188.169.57.232:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
