fileServerAddr: 10.114.0.2
gatewayUrl: https://service.onday.ge
env: prod
defaultTenant: dreamland

tenants:
  datasources:
    dev:
      url: jdbc:postgresql://10.114.0.11:2552/dev_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: Onday#2024
    dreamland:
      url: jdbc:postgresql://10.114.0.11:2552/dreamland_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: Onday#2024
    ecowood:
      url: jdbc:postgresql://10.114.0.11:2552/ecowood_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: Onday#2024
    elmontage:
      url: jdbc:postgresql://10.114.0.11:2552/elmontage_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: Onday#2024
    biblusi:
      url: jdbc:postgresql://10.114.0.11:2552/biblusi_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: Onday#2024


tenant:
  mappings:
    biblusi: "biblusi"
    elmontage: "elmontage"
    dreamland: "dreamland"
    ecowood: "ecowood"
    test: "dev"
    dev: "dev"
    gravita: "dev"
    ig: "dev"
    bdo: "dev"
    liongroup: "dev"
    logistica: "dev"
    schoolprogress: "dev"
    wds: "dev"
    caucaspack: "dev"
