defaultTenant: biblus_test
defaulttmtenants: biblus_test

tenants:
  datasources:
    biblus_test:
      url: jdbc:postgresql://192.168.100.5:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    dev:
      url: jdbc:postgresql://192.168.100.5:5432/dev_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
      
      

            
tmtenants:
  datasources:
    biblus_talent:
      url: jdbc:postgresql://192.168.100.5:5432/talent_management_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike