defaultTenant: elmontage
dfdefaultTenant: elmontage

tenants:
  datasources:
    ec:
      url: jdbc:postgresql://localhost:5432/ec_administrative_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
    elmontage:
      url: jdbc:postgresql://localhost:5432/administrative_db?currentSchema=elmontage
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
      
dftenants:
  datasources:
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_docflow_db1
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
    elmontage:
      url: jdbc:postgresql://localhost:5432/elmontage_docflow_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022