fileServerAddr: 209.38.238.190
gatewayUrl: http://localhost:8782
env: dev

defaultTenant: dev

tenants:
  datasources:
    dev:
      url: jdbc:postgresql://192.168.100.15:5432/dev_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    
    
tenant:
  mappings:
    # Primary and secondary database isolation (one-to-one mapping)
    isolated:
      biblusi: biblusi
      elmontage: elmontage
      dreamland: dreamland
      ecowood: ecowood

    # Shared primary and secondary databases (one-to-many mapping)
    shared:
      biblus_test:
        - biblus_test
        - ta
      dev:
        - demo
        - test
        - dev
        - gravita
        - ig
        - bdo
        - liongroup
        - logistica
        - schoolprogress
        - wds
        - caucaspack

      
