defaultTenant: biblus

tenants:
  datasources:
    ess:
      url: jdbc:postgresql://94.43.157.75:5432/administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    biblus:
      url: jdbc:postgresql://94.43.157.75:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
