envs:
    test:
      url: jdbc:postgresql://192.168.100.6:5432/administrative_db
      username: tornike
      driverClassName: org.postgresql.Driver
      password: tornike
    prod:
      url: jdbc:postgresql://192.168.100.6:5432/administrative_db2
      username: tornike
      driverClassName: org.postgresql.Driver
      password: tornike
  