defaultTenant: biblus
dfdefaultTenant: biblus

tenants:
  datasources:
    ess:
      url: jdbc:postgresql://localhost:5432/administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
      
dftenants:
  datasources:
    ess:
      url: jdbc:postgresql://localhost:5432/docflow_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
