fileServerAddr: 209.38.238.190
gatewayUrl: http://localhost:8782
env: dev

defaultTenant: dev

tenants:
  datasources:
    biblusi:
      url: jdbc:postgresql://192.168.100.15:5432/biblusi_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    dev:
      url: jdbc:postgresql://192.168.100.15:5432/dev_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike