fileServerAddr: 209.38.238.190
gatewayUrl: http://localhost:8782
env: dev

defaultTenant: biblus_test

tenants:
  datasources:
    biblus_test:
      url: jdbc:postgresql://94.43.157.75:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike