fileServerAddr: 209.38.238.190
gatewayUrl: http://localhost:8782
env: dev
configServerIp: 206.189.63.160

defaultTenant: biblus_test

tenants:
  datasources:
    biblus_test:
      url: jdbc:postgresql://192.168.100.5:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike