defaultTenant: elmontage
dfdefaultTenant: elmontage

tenants:
  datasources:
    biblusi:
      url: jdbc:postgresql://private-db-postgresql-fra1-42513-do-user-8524462-0.c.db.ondigitalocean.com:25061/biblus_administrative_db?sslmode=require
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: AVNS_3ehU5CzxHJKa9bPo_lc
    elmontage:
      url: jdbc:postgresql://private-db-postgresql-fra1-42513-do-user-8524462-0.c.db.ondigitalocean.com:25061/elmontage_administrative_db?sslmode=require
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: AVNS_3ehU5CzxHJKa9bPo_lc
    dev:
      url: jdbc:postgresql://private-db-postgresql-fra1-42513-do-user-8524462-0.c.db.ondigitalocean.com:25061/dev_administrative_db?sslmode=require
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: AVNS_3ehU5CzxHJKa9bPo_lc
      
dftenants:
  datasources:
    biblusi:
      url: jdbc:postgresql://private-db-postgresql-fra1-42513-do-user-8524462-0.c.db.ondigitalocean.com:25061/biblus_docflow_db?sslmode=require
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: AVNS_3ehU5CzxHJKa9bPo_lc
    elmontage:
      url: jdbc:postgresql://private-db-postgresql-fra1-42513-do-user-8524462-0.c.db.ondigitalocean.com:25061/elmontage_docflow_db?sslmode=require
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: AVNS_3ehU5CzxHJKa9bPo_lc
    dev:
      url: jdbc:postgresql://private-db-postgresql-fra1-42513-do-user-8524462-0.c.db.ondigitalocean.com:25061/dev_docflow_db?sslmode=require
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: AVNS_3ehU5CzxHJKa9bPo_lc