defaultTenant: biblus
dfdefaultTenant: biblus

tenants:
  datasources:
    ec:
      url: jdbc:postgresql://localhost:5432/ec_administrative_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
    elmontage:
      url: jdbc:postgresql://onday_pg:AVNS_6NWau5Mi9u_WxraWW4v@db-postgresql-nyc1-31273-do-user-8524462-0.b.db.ondigitalocean.com:25061/elmontage_administrative_db?sslmode=require
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: AVNS_6NWau5Mi9u_WxraWW4v
      
dftenants:
  datasources:
    ess:
      url: jdbc:postgresql://localhost:5432/docflow_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_docflow_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
