defaultTenant: biblus
dfdefaultTenant: biblus

tenants:
  datasources:
    ec:
      url: jdbc:postgresql://localhost:5432/ec_administrative_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
    elmontage:
      url: jdbc:postgresql://db-postgresql-nyc1-96233-do-user-8524462-0.b.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      driverClassName: org.postgresql.Driver
      username: doadmin
      password: AVNS_Vnr4BR7bEBqi1gcqCsu
      
dftenants:
  datasources:
    ess:
      url: jdbc:postgresql://localhost:5432/docflow_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    biblus:
      url: jdbc:postgresql://localhost:5432/biblus_docflow_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: OnDay#2022
