fileServerAddr: 10.114.0.2
gatewayUrl: http://10.114.0.13
env: prod
defaultTenant: dev

tenants:
  datasources:
    dev:
      url: jdbc:postgresql://10.114.0.13:2552/dev_db
      driverClassName: org.postgresql.Driver
      username: onday_pg
      password: Onday#2024Demo