defaultTenant: biblus_test
dfdefaultTenant: biblus_test
defaulttmtenants: biblus_talent

tenants:
  datasources:
    biblus_test:
      url: jdbc:postgresql://192.168.100.5:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    elmontage:
      url: jdbc:postgresql://192.168.100.5:5432/elmontage_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    dev:
      url: jdbc:postgresql://192.168.100.5:5432/dev_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
      
      
      
dftenants:
  datasources:
    biblus_test:
      url: jdbc:postgresql://192.168.100.5:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    dev:
      url: jdbc:postgresql://192.168.100.5:5432/dev_docflow_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
            
tmtenants:
  datasources:
    biblus_talent:
      url: jdbc:postgresql://192.168.100.5:5432/talent_management_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike