defaultTenant: ess
dfdefaultTenant: ess

tenants:
  datasources:
    ess:
      url: jdbc:postgresql://192.168.100.6:5432/administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    biblus:
      url: jdbc:postgresql://192.168.100.6:5432/biblus_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
      
      
dftenants:
  datasources:
    ess:
      url: jdbc:postgresql://192.168.100.6:5432/docflow_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
