fileServerAddr: 209.38.238.190
gatewayUrl: http://localhost:8782
env: dev

defaultTenant: dev

tenants:
  datasources:
    dev:
      url: jdbc:postgresql://192.168.100.15:5432/dev_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    
tenant:
  mappings:
    biblusi: "biblusi"
    elmontage: "elmontage"
    dreamland: "dreamland"
    ecowood: "ecowood"
    biblus_test: "biblus_test"
    ta: "biblus_test"
    demo: "dev"
    test: "dev"
    dev: "dev"
    gravita: "dev"
    ig: "dev"
    bdo: "dev"
    liongroup: "dev"
    logistica: "dev"
    schoolprogress: "dev"
    wds: "dev"
    caucaspack: "dev"
