server:
  port: 1213   #default port where the service will be started
  error:
    whitelabel:
      enabled: off
    path: /error
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8781/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        envers:          
          autoRegisterListeners: true
          revision_on_collection_change: false
      org:
        hibernate:
            envers:
              store_data_at_delete: true
            
            
        dialect: org.hibernate.dialect.PostgreSQLDialect
        multiTenancy: DATABASE
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        types:
          print:
            banner: false
    generate-ddl: true

  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  
  application:
    name: docflow-service

  cloud:
    compatibility-verifier:
      enabled: false
  loadbalancer:
    ribbon:
      enable: false
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8765
        auto-registration: true
        api-path: /instances
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        envers: DEBUG


feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

management:
  endpoints:
    web:
      exposure:
        include: "*"
