server:
  port: 8783   #default port where the service will be started


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


  application:
    name: gateway-server


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    multipart:
      location: /data/upload_tmp
  cloud:
    config:
      server:
        git:
          uri:

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    fetch-registry: true
    register-with-eureka: true

zuul:
  routes:
    hr-administrative-service:
      path: /administrative/**
      serviceId: hr-administrative-service
      sensitiveHeaders:
    hr-account-service:
      path: /account/**
      sensitiveHeaders:
      serviceId: HR-ACCOUNT-SERVICE
    docflow-service:
      path: /docflow/**
      sensitiveHeaders:
      serviceId: DOCFLOW-SERVICE
    file-service:
      path: /file/**
      sensitiveHeaders:
      serviceId: FILE-SERVICE

  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 300000
    connect-timeout-millis: 300000
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 90000
  ReadTimeout: 90000


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
management:
  security:
    enabled: false
  server:
    port: 9000


defaultTenant: ess

tenants:
  datasources:
    ess:
      url: jdbc:postgresql://188.169.57.232:5432/administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
    retailgroup:
      url: jdbc:postgresql://188.169.57.232:5432/retailgroup_administrative_db
      driverClassName: org.postgresql.Driver
      username: tornike
      password: tornike
