server:
  port: 8782   #default port where the service will be started
  max-http-header-size: 10000000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      generate-ddl: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:8081
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8765
        auto-registration: true
        api-path: /instances

  application:
    name: gateway-server
  flyway:
    baseline-on-migrate: true
    enabled: true
    #user: tornike
    #password: tornike
    baseline-description: "init"
    baseline-version: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    multipart:
      location: /data/upload_tmp

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hr-administrative-service
          uri: lb://hr-administrative-service
          predicates:
            - Path=/administrative/**
          filters:
            - RewritePath=/administrative/(?<path>.*), /$\{path}
        - id: share-config-service
          uri: lb://share-config-service
          predicates:
            - Path=/share-config/**
          filters:
            - RewritePath=/share-config/(?<path>.*), /$\{path}
        - id: DOCFLOW-SERVICE
          uri: lb://DOCFLOW-SERVICE
          predicates:
            - Path=/docflow/**
          filters:
            - RewritePath=/docflow/(?<path>.*), /$\{path}
eureka: #tells about the Eureka server details and its refresh time
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5
    registry-fetch-interval-seconds: 30


  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 300000
    connect-timeout-millis: 300000
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 90000
  ReadTimeout: 90000


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
management:
  security:
    enabled: false
  server:
    port: 9000


