server:
  port: 8782   #default port where the service will be started
  connection-timeout: 90000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


  application:
    name: gateway-server


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    multipart:
      location: /data/upload_tmp
  cloud:
    config:
      server:
        git:
          uri:


eureka: #tells about the Eureka server details and its refresh time
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5
    registry-fetch-interval-seconds: 30
    fetch-registry: true
    register-with-eureka: true

zuul:
  routes:
    hr-administrative-service:
      path: /administrative/**
      serviceId: hr-administrative-service
      sensitiveHeaders:
    share-config-service:
      path: /share-config/**
      sensitiveHeaders:
      serviceId: share-config-service
    docflow-service:
      path: /docflow/**
      sensitiveHeaders:
      serviceId: DOCFLOW-SERVICE
    file-service:
      path: /file/**
      sensitiveHeaders:
      serviceId: FILE-SERVICE

  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 900000
    connect-timeout-millis: 900000
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 150000
  ReadTimeout: 150000


logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off
management:
  security:
    enabled: false
  server:
    port: 9000


