server:
  port: 1212   #default port where the service will be started
  error:
    whitelabel:
      enabled: off
    path: /error

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 3
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8781/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      org:
        hibernate:
          envers:
            autoRegisterListeners: true
            store_data_at_delete: true
            revision_on_collection_change: false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        types:
          print:
            banner: false
    generate-ddl: true

      
  application:
    name: hr-administrative-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    #user: tornike
    #password: tornike
    baseline-description: "init"
    baseline-version: 0


logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off


security-properties:
  security:
    encryptionSecretKey: S0942MmGA8Ek

