server:
  port: 1212   #default port where the service will be started
  max-http-header-size: 10000000
  error:
    whitelabel:
      enabled: off
    path: /error
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    prefer-ip-address: true
    #hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8781/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      org:
        hibernate:
          envers:
            autoRegisterListeners: true
            store_data_at_delete: true
            revision_on_collection_change: false
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        types:
          print:
            banner: false
    generate-ddl: true

  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  
  application:
    name: hr-administrative-service

  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    #user: tornike
    #password: tornike
    baseline-description: "init"
    baseline-version: 0
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8765
        auto-registration: true
        api-path: /instances

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000


        
jodconverter:
  local:
    enabled: true
    port-numbers: 2002
    kill-existing-process: true
    process-timeout: 250000
    process-retry-interval: 1000
    max-tasks-per-process: 200
    task-execution-timeout: 250000
    task-queue-timeout: 90000
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages
            
            
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
