server:
  port: 1220   #default port where the service will be started
  error:
    whitelabel:
      enabled: off
    path: /error


eureka:         #tells about the Eureka server details and its refresh timejugh
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8781/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: ge.onday.shareconfigserver.util.ProjectPostgreSQL95Dialect
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    mongodb:
      loggerdb:
       uri: mongodb://onday_logger:demo1989ErrorLogger@10.114.0.13:27090/?authSource=logger_db
      attachmentdb:
       uri: mongodb://onday_logger:demo1989ErrorLogger@10.114.0.13:27090/?authSource=file_attachment_db

  application:
    name: share-config-service
  datasource:
    url: jdbc:postgresql://10.114.0.13:2552/config_service_db
    username: onday_pg
    password: Onday#2024Demo

  boot:
    admin:
      client:
        enabled: true
        url: http://10.114.0.13:8765
        auto-registration: true
        api-path: /instances

  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off


clamd:
  host: 10.114.0.13
  port: 3310
  timeout: 25000
