server:
  port: 1220   #default port where the service will be started
  error:
    whitelabel:
      enabled: off
    path: /error

eureka: #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8781/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5
    registry-fetch-interval-seconds: 30

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: ge.onday.shareconfigserver.util.ProjectPostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        generate_statistics: false
        show_sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    mongodb:
      loggerdb:
       uri: mongodb://onday_logger:demo1989ErrorLogger@154.6.141.122:27090/?authSource=logger_db
      attachmentdb:
       uri: mongodb://onday_logger:demo1989ErrorLogger@154.6.141.122:27090/?authSource=file_attachment_db
      

  application:
    name: share-config-service
  datasource:
    url: jdbc:postgresql://192.168.100.15:5432/app_config_service_db
    username: tornike
    password: tornike



  cloud:
    compatibility-verifier:
      enabled: false
  loadbalancer:
    ribbon:
      enable: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    ignore-migration-patterns:
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8765
        auto-registration: true
        api-path: /instances
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
management:
  endpoints:
    web:
      exposure:
        include: "*"
clamd:
  host: 154.6.141.122
  port: 3310
  timeout: 25000
  